### ISSUE TITLE
Get the text to be printed and the configuration table

### ISSUE THREAD

**Issue by Positive07** [adonaac/popo#1]
First, amazing work! Your implementation on this is amazing!

And now to the proposal, I would love having some methods to set and get the text.

Setting the text can also be splitted in setting (overwriting the old text), apending and prepending (adding text to the end, beggining)

Getting the text could be splitted in getting the String as it will be rendered (`[popo](func)` would return `popo`) and getting the text as it is (`[popo](func)` would return `[popo](func)`

Are these possible? Do you need help on implementing them?

**Comment by adonaac** [comment]
Please provide me with a few complete examples where those requests would be useful.

**Comment by Positive07** [comment]
Setting the text is as easy as creating a new object, but I'm not sure how to get the string so that I can modify it, say:

````lua
text = Text(
    "[My new text](fun) [with some functions](fi)",
    {fu = function () end, fi = function () end}
)
--So how do I know what the text object is gonna print to the screen now? 
--I would need somehow to get the character table or something similar
--but I dont see that being really possible

print(text) --I would expect the ouput to be "My text with some functions"
print(text:original()) --"[My new text](fun) [with some functions](fi)" the original name is just to call it something

--With text:original() I could create a new text wich is a modification of the old one:
text2 = Text(
    text:original().." [I can add text now!](fu)",
    {
        fun=function() end;
        fi = function() end
        fu = function() end
    }
)
print(text) --My text with some functions I can add text now!
```

**Comment by adonaac** [comment]
You can get the original by doing text.text. As for what's going to be printed on the screen I'll add an attribute for that.

**Comment by Positive07** [comment]
Oh great! I didnt know it was there sorry... Is the configuration table there too?

**Comment by adonaac** [comment]
The configuration table is not. I'll add it too along with the what's going to be printed on the screen attribute.

**Comment by Positive07** [comment]
Thanks! This will be really useful

**Comment by adonaac** [comment]
The configuration table can now be accessed via `text.config` and the string as it will be printed on the screen via `text.str_text`.
