### ISSUE TITLE
Line break '\n' doesn't really work correctly.

### ISSUE THREAD

**Issue by Kiraffi** [adonaac/popo#2]
Using line breaks: '\n' causes some weird printing. It keeps spamming several letters on top of each other where the line break should be

**Comment by adonaac** [comment]
Try '@n'. Forgot to document that.

**Comment by Positive07** [comment]
Could you automatically replace `\n` with `@n` inside your lib? That would be amazing, as I suggested in a comment in the commit that is really easy
