### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by Positive07** [adonaac/popo#3]
As someone said in the forum align right or center would be nice, align-center is possible as we said, I guess that align right should be possible the same way, if you dont divide by two.
If you dont want to implement them directly in the library you could put both functions in the readme:
* Center:
```lua
function n(dt, c)
    c.x = c.x + (love.graphics.getWidth() - c.text.font:getWidth(c.str_text))/2
end
```
* Right
```lua
function n(dt, c)
    c.x = c.x + (love.graphics.getWidth() - c.text.font:getWidth(c.str_text))
end
```

**Comment by adonaac** [comment]
Alignment only makes sense if wrap_width is set to some value. Even then, this is not high on my priorities and it's probably not as easy to implement either, so I'll leave this open for later.
