### ISSUE TITLE
Text width from text object if using multiple fonts

### ISSUE THREAD

**Issue by adonaac** [adonaac/popo#5]
After implementing #4, the text width may not simply be `text.font:getWidth(text.str_text)` because there will be multiple fonts in play. Create an attribute `text.w` that always returns the correct text width. Same for height I guess?

**Comment by Positive07** [comment]
I dont think this is needed, how would you handle this:
```lua
fuction n (dt,c)
    time = time + dt
    if time > 1 then
        c.font = myfont
    end
end
```
Same applies to scale, when you scale a letter it is your problem if it doesnt look right, not a problem with the library

**Comment by adonaac** [comment]
I can just set that attribute every frame so it'll be always right. This will make it easier to center the entire text on the screen for instance, because to do that you need to know its width/height.

**Comment by Positive07** [comment]
Not totally convinced, I think the best would be to give the width with the normal font, if you make changes in sizes of letter or font then it is your own problem...

**Comment by Positive07** [comment]
Unless you decide to handle fonts outside functions, say
```lua
text = Text("some text which has [a bold part](bold)",{
    font = love.graphics.newFont("normal.ttf",14),
    bold = love.graphics.newFont("bold.ttf",15),
    ...
}
```

**Comment by adonaac** [comment]
When you do `text:draw(x, y)`, if you want the text to be centered on the screen, you need to know its width so you can choose a proper x, like:
```lua
text:draw(love.graphics.getWidth()/2 - text.w, y)
```
If you don't have the `text.w` as information you can't do this.

>Unless you decide to handle fonts outside functions, say
This issue is unrelated to how I'm gonna handle fonts specifically.

**Comment by Positive07** [comment]
It would be great to have this information, I understand what you mean, but as you have pointed it would be useful after `text:update(dt)` and not inside it, so you wouldnt be able to use it inside of the functions that modify the characters.
```lua
text:draw(love.graphics.getWidth()/2 - text.w, y)
```
This wont draw the text centered if it contains multiple lines, it would be great though, having something that could do this

**Comment by adonaac** [comment]
If it has multiple lines either `wrap_width` is set and then you already have a width, or your text breaks lines with `@n`. In that case it makes sense to just take the longest line.

**Comment by Positive07** [comment]
Yeah, then I'm totally fine with how you intend to do it!
Another way would be to have a `text.lines` table with all the lines and somehow modify them... Just a though not sure how it would work
