### ISSUE TITLE
Word wrap

### ISSUE THREAD

**Issue by adonaac** [adonaac/popo#6]
https://www.love2d.org/forums/viewtopic.php?f=5&t=79495#p179091

Create an attribute `text.word_wrap` which when set to true will force wrapping to only happen on spaces. Make sure it absolutely never goes over `wrap_width`.

**Comment by Positive07** [comment]
I think that the best would be to wrap words normally, and just text wrap looooooooooooong words, I have [a gist with a custom printf](https://gist.github.com/Positive07/2eccf6aff9b135982c75) which does just thos
